version: '${VERSION}'
services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone-mysql
    environment:
      - MYSQL_SERVICE_HOST=${HOSTIP}
    env_file:
      - ./nacos-standlone-mysql.env
    volumes:
      - ~/docker_data/nacos/logs:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"