version: '${VERSION}'
services:
  zoo:
    container_name: zookeeper
    image: zookeeper:${ZOOKEEPER_VERSION}
    restart: always
    ports:
      - '2181:2181'
    volumes:
      - ~/docker_data/zookeeper/data:/data
      - ~/docker_data/zookeeper/datalog:/datalog
    environment:
      TZ: 'Asia/Shanghai'
      ZOO_4LW_COMMANDS_WHITELIST: '*'
      JVMFLAGS: "-Xmx1024m -Djute.maxbuffer=10485750"