version: '3.6'
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.6.2
    restart: always
    ports:
      - '2181:2181'
    volumes:
      - '../../tempdata/zoo/data:/data'
      - '../../tempdata/zoo/datalog:/datalog'
    environment:
      TZ: 'Asia/Shanghai'
      ZOO_4LW_COMMANDS_WHITELIST: '*'