version: ${VERSION}
services:
  portainer_service:
    image: portainer/portainer-ce:${PORTAINER_CE_TAG}
    container_name: portainer-ce
    restart: always
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    deploy:
      resources:
        limits:
          memory: 128M

volumes:
  portainer:
    external: true

networks:
  default:
    name: zion
    external: true