version: '3.6'
services:
  zookeeper:
    container_name: zookeeper_aiman
    image: zookeeper:3.6.2
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "../../tempdata/zoo/data:/data"
      - "../../tempdata/zoo/datalog:/datalog"
    environment:
      TZ: 'Asia/Shanghai'
  kafka:
    container_name: kafka_aiman
    image: wurstmeister/kafka:2.13-2.7.0
    restart: always
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
    environment:
      TZ: 'Asia/Shanghai'
      # 本机在局域网(内部访问)或外网IP(外网访问)
      KAFKA_ADVERTISED_HOST_NAME: 10.1.68.177
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.1.68.177:9092
      KAFKA_HOST_NAME: 0.0.0.0
      KAFKA_PORT: 9092
      # PLAINTEXT://:9092 等同于 PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "aiman:1:1"
  kafdrop:
    container_name: kafdrop_aiman
    image: obsidiandynamics/kafdrop:3.27.0
    restart: always
    depends_on: [ kafka ]
    ports:
      - "9000:9000"
    environment:
      TZ: 'Asia/Shanghai'
      KAFKA_BROKERCONNECT: kafka:9092
      SERVER_SERVLET_CONTEXTPATH: "/aiman"