version: ${VERSION}
services:
  mysql:
    image: adguard/adguardhome:${TAG}
    restart: always
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 68:68/udp
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
      - 3000:3000/tcp
      - 853:853/tcp
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    env_file:
      - ../.env
    volumes:
      - ~/docker_data/adguardhome/work:/opt/adguardhome/work\
      - ~/docker_data/adguardhome/conf:/opt/adguardhome/conf\