version: '${VERSION}'
services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone-mysql
    restart: always
    environment:
      - MYSQL_SERVICE_HOST=mysql
      # - NACOS_AUTH_ENABLE=true
      - JVM_XMS=256m
      - JVM_XMX=256m
    env_file:
      - nacos-standlone-mysql.env
    volumes:
      - nacos:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
  sentinel:
    image: bladex/sentinel-dashboard:${SENTINEL_VERSION}
    container_name: sentinel-dashboard
    restart: always
    ports:
      - "8080:8858"

volumes:
  nacos:
    external: true

networks:
  default:
    name: zion
    external: true