version: ${VERSION}
services:
  jenkins:
    image: jenkinsci/blueocean:${BLUEOCEAN_TAG}
    restart: always
    ports:
      - 58080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkinsdata:
    external: true

networks:
  default:
    name: zion
    external: true