version: '3'
services:
    rabbitmq-container1:
        container_name: rabbitmq_master
        image: rabbitmq:management
        hostname: rabbitmq_host
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            # RABBITMQ_NODENAME: mqmaster
            RABBITMQ_ERLANG_COOKIE: myerlangcookie
    rabbitmq-container2:
        container_name: rabbitmq_slave1
        image: rabbitmq:management
        hostname: rabbitmq_host1
        ports:
            - "5673:5672"
            - "15673:15672"
        environment:
            # RABBITMQ_NODENAME: mqslave1
            RABBITMQ_ERLANG_COOKIE: myerlangcookie
        depends_on: 
            - rabbitmq-container1
        links:
            #关联主节点的hostname，方便容器内互相访问
            - rabbitmq-container1:rabbitmq_host
    rabbitmq-container3:
        container_name: rabbitmq_slave2
        image: rabbitmq:management
        hostname: rabbitmq_host2
        ports:
            - "5674:5672"
            - "15674:15672"
        environment:
            # RABBITMQ_NODENAME: mqslave1
            RABBITMQ_ERLANG_COOKIE: myerlangcookie
        depends_on: 
            - rabbitmq-container1
            - rabbitmq-container2
        links:
            - rabbitmq-container1:rabbitmq_host
            - rabbitmq-container2:rabbitmq_host1