version: ${VERSION}
services:
  registry:
    image: registry:${REGISTRY_TAG}
    restart: always
    privileged: true
    container_name: registry
    environment:
      - REGISTRY_AUTH=d4a6f7c2cbe8be01
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry_Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/passwd
    ports:
      - 5000:5000
    volumes:
      - registry:/var/lib/registry
    deploy:
      resources:
        limits:
          memory: 32M
  registry-web:
    image: konradkleine/docker-registry-frontend:${REGISTRY_FRONTEND_TAG}
    restart: always
    container_name: registry-web
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000
      # - ENV_USE_SSL=yes
    ports:
      # - 5443:443
      - 5001:80
    volumes:
      - ./apache2/server.crt:/etc/apache2/server.crt:ro
      - ./apache2/server.key:/etc/apache2/server.key:ro
    deploy:
      resources:
        limits:
          memory: 32M

volumes:
  registry:
    external: true

networks:
  default:
    name: zion
    external: true