version: ${VERSION}
services:
  registry:
    image: registry:${REGISTRY_TAG}
    restart: always
    privileged: true
    container_name: registry
    ports:
      - 5000:5000
    volumes:
      - registry:/var/lib/registry
    deploy:
      resources:
        limits:
          memory: 32M
  web:
    image: konradkleine/docker-registry-frontend:${REGISTRY_FRONTEND_TAG}
    links:
      - registry:zion-docker-registry.com
    restart: always
    ports:
      - 5001:80
    environment:
      - ENV_DOCKER_REGISTRY_HOST=zion-docker-registry.com #配置links的自定义名字
      - ENV_DOCKER_REGISTRY_PORT=5000
    deploy:
      resources:
        limits:
          memory: 32M

volumes:
  registry:
    external: true

networks:
  default:
    name: zion
    external: true