version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: 10.1.60.92 #外网IP
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop
    depends_on: [ kafka ]
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      SERVER_SERVLET_CONTEXTPATH: "/aiman"
#   zkui:
#     # container_name: zkui
#     image: qnib/zkui
#     depends_on: [ zookeeper ]
#     restart: "no"
#     ports:
#       - "9090:9090"
#     environment:
#       ZKUI_ZK_SERVER: zookeeper:2181
    #   ZKUI_ADMIN_PW: asiainfo_zk
#   rabbitmq:
#     container_name: rabbitmq
#     image: rabbitmq:management
#     ports:
#       - "15672:15672"
#       - "5672:5672"
#     volumes:
#       - /root/rabbitdata:/var/lib/rabbitmq
#     environment:
#       RABBITMQ_DEFAULT_USER: root
#       RABBITMQ_DEFAULT_PASS: asiainfo_root
#       RABBITMQ_DEFAULT_VHOST: /aiman