version: '${VERSION}'
services:
  seata-server:
    image: seataio/seata-server:${SEATA_VERSION}
    hostname: seata-server
    container_name: seata-server
    ports:
      - "8091:8091"
      - "7091:7091"
    environment:
      # 指定seata服务启动端口
      - SEATA_PORT=8091
      # 注册到nacos上的ip。客户端将通过该ip访问seata服务。
      # 注意公网ip和内网ip的差异。
      - SEATA_IP=${HOSTIP}
    volumes:
      - "./seata-server/resources/application.yml:/seata-server/resources/application.yml"