version: ${VERSION}

services:

  mongo:
    image: mongo:${MONGO_TAG}
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: yapi
    volumes:
      - ~/docker_data/mongo/db:/data/db
      - ./init:/docker-entrypoint-initdb.d/

  mongo-express:
    image: mongo-express:${MONGO_EXPRESS_TAG}
    restart: always
    container_name: mongo-express
    depends_on: [ mongo ]
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: express
      ME_CONFIG_BASICAUTH_PASSWORD: express
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

networks:
  default:
    name: zion