version: ${VERSION}
services:
  mysql:
    image: mysql:${MYSQL_TAG}
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    env_file:
      - ./mysql.env
    volumes:
      - mysql:/var/lib/mysql
      # 自定义cnf
      # 注意 windows上面使用下面方式自定义配置，需要将目录里面的.cnf文件设置为只读（也有说将项目移至 用户目录下面即可，不如只读文件来的更好些）
      - ./conf.d:/etc/mysql/conf.d
      # 自定义初始化sql
      - ./initdb.d:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  mysql:
    external: true

networks:
  default:
    name: zion
    external: true